name: Build

on:
  push:
    branches:
      - main
jobs:
  - name: Run Gitleaks
    id: gitleaks
    uses: DariuszPorowski/github-action-gitleaks@v2
    with:
    report_format: sarif
    fail: false

# (optional) It's just to see outputs from the Action
  - name: Get the output from the gitleaks step
    run: |
      echo "exitcode: ${{ steps.gitleaks.outputs.exitcode }}"
      echo "result: ${{ steps.gitleaks.outputs.result }}"
      echo "output: ${{ steps.gitleaks.outputs.output }}"
      echo "command: ${{ steps.gitleaks.outputs.command }}"
      echo "report: ${{ steps.gitleaks.outputs.report }}"

  - name: Upload Gitleaks SARIF report to code scanning service
    if: ${{ steps.gitleaks.outputs.exitcode == 1 }}
    uses: github/codeql-action/upload-sarif@v2
    with:
      sarif_file: ${{ steps.gitleaks.outputs.report }}
